repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# 1. Security Check for Terraform
-   repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.1
    hooks:
    -   id: tfsec

# 2. Custom Policy Check (Rego)
-   repo: https://github.com/open-policy-agent/conftest
    rev: v0.45.0
    hooks:
    -   id: conftest
        args: ["test", "--policy", "policy/"]

# 3. Python/Django Formatter
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black


repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=88", "--extend-ignore=E203"]